### ISSUE TITLE
Variable accessed before assignment

### ISSUE THREAD

**Issue by peterschen** [GoogleCloudPlatform/gce-automated-ad-join#13]
When trying to join a computer to the domain the following exception is being raised:

```
ERROR:root:Creating computer account for 'build' in 'OU=cbp-sandbox,OU=Projects,OU=sandbox.lab,DC=sandbox,DC=lab' failed
Traceback (most recent call last):
  File "/register-computer/main.py", line 351, in __register_computer
    mig_info = __get_managed_instance_group_for_instance(gce_instance)
  File "/register-computer/main.py", line 119, in __get_managed_instance_group_for_instance
    if (metadata_created_by and "instanceGroupManagers" in metadata_created_by["value"]):
UnboundLocalError: local variable 'metadata_created_by' referenced before assignment
```

The indentation of [the code block in main.py](https://github.com/peterschen/gce-automated-ad-join/blob/master/ad-joining/register-computer/main.py#L108-L119) seems to be wrong as it attempts to access the variable before being assigned.

**Comment by idofl** [comment]
Fixed directly in master.
https://github.com/GoogleCloudPlatform/gce-automated-ad-join/commit/21927bad9e63782db2343a32a9c28b722f84e1e8
