### ISSUE TITLE
cleanup endpoint ad_site

### ISSUE THREAD

**Issue by jkattmann** [GoogleCloudPlatform/gce-automated-ad-join#40]
When the `__cleanup_computers` function runs it calls `__connect_to_activedirectory()` without the `ad_site` (obtained from the query string). See: https://github.com/GoogleCloudPlatform/gce-automated-ad-join/blob/890a8322ebe0854ee87e48d4bc961990549c432c/ad-joining/register-computer/main.py#L579

The `__register_computer` function does it properly, see https://github.com/GoogleCloudPlatform/gce-automated-ad-join/blob/890a8322ebe0854ee87e48d4bc961990549c432c/ad-joining/register-computer/main.py#L294

This seems like a bug any thoughts?

**Comment by peterschen** [comment]
Can confirm  that this is a bug. I've submitted a PR that'll fix this.
